### ISSUE TITLE
number of chunks

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeo#11]
I think the number of chunks may be calculated incorrectly.
Question: are the following three lines of code correct?

In SparseFeaturesChunk.cpp line 40:
`int chunksInX = static_cast<int>(std::ceil(static_cast<float>(_hiddenSize.x) / static_cast<float>(_chunkSize.x)));`

In SparseFeaturesChunk.cpp line 80 and 290:
`int chunksInX = _hiddenSize.x / _chunkSize.x + 1;`

Regards HJ!

**Comment by 222464** [comment]
Good catch! I don't think it makes a difference in terms of performance, but it should definitely be consistent. Will fix!

**Comment by HJLebbink** [comment]
It crashes on line 110 in neoKernelsSparseFeaturesChunk.cl
`write_imagei(chunkWinners, chunkPosition, (int4)(maxDelta.x, maxDelta.y, 0, 0));`
with chunkPosition = (7,8) due to an out of range memory write.

That is, when porting it to C++, not sure why OpenCL wouldn't find it offensive.

Regards HJ!
