### ISSUE TITLE
pooled layer swamps

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeo#14]
Can you guys please explain why scale in FeatureHierarchy.fhPool is not used (see below). If ignoring the this scale and if you take a long pooling window, I think the pooled layer may swamp the influx from the next layer. Or am I mistaken?

```
void kernel fhPool(read_only image2d_t states, read_only image2d_t outputsBack, write_only image2d_t outputsFront, float scale) {
    int2 position = (int2)(get_global_id(0), get_global_id(1));
    float state = read_imagef(states, defaultSampler, position).x;
    float outputPrev = read_imagef(outputsBack, defaultSampler, position).x;
    write_imagef(outputsFront, position, (float4)(fmax(outputPrev, state), 0.0f, 0.0f, 0.0f));
}
```

**Comment by 222464** [comment]
We are experimenting with two forms of pooling (average and max pooling). Average pooling requires the scaling, and max pooling does not. The source of the confusion here is probably that the pooling layer is actually cleared between each cycle of a layer. It is reset to 0, so there hopefully isn't any swamping :)

The scale is used in the average pooling to keep the value in the [0, 1] range.

**Comment by HJLebbink** [comment]
Thanks, yes that makes sense.
