### ISSUE TITLE
Adding 0.5f to int

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeo#17]
Hi

In https://github.com/ogmacorp/OgmaNeo/blob/master/resources/kernels/neoKernelsSparseFeaturesChunk.cl on line 32:
```
int2 chunkPosition = (int2)(hiddenPosition.x / chunkSize.x, hiddenPosition.y / chunkSize.y);
int2 chunkCenter = (int2)(chunkPosition.x + 0.5f, chunkPosition.y + 0.5f);
```
Is not a severe bug, but it is probably not what you wanted.

**Comment by 222464** [comment]
Good catch! Will fix!

**Comment by rcrowder** [comment]
Fixed in PR https://github.com/ogmacorp/OgmaNeo/pull/18
