### ISSUE TITLE
A public place to discuss stuff ?

### ISSUE THREAD

**Issue by khaotik** [ogmacorp/OgmaNeo#19]
I understand the project just started, but is there a public place to discuss stuff relating to OgmaNeo? Like, a mailing list, or forums?

Sorry for posting this message on github issue tracker.

**Comment by jg1141** [comment]
I'd be interested in joining [https://ogmaneo.slack.com/](https://ogmaneo.slack.com/) if that existed.

**Comment by 222464** [comment]
We created a gitter now, [https://gitter.im/ogmaneo](https://gitter.im/ogmaneo) !
