### ISSUE TITLE
Go lang bindings for OgmaNeo

### ISSUE THREAD

**Issue by rcrowder** [ogmacorp/OgmaNeo#22]
cc @nytopop

A recent request was made for a Go lang version of OgmaNeo. This issue is to document the findings I've made with respect to evaluating whether [SWIG](http://www.swig.org) (Simplified Wrapper and Interface Generator) can be used to produce these Go bindings.

During prototyping we had a [Go lang](https://golang.org/) version of a pre-release version of OgmaNeo. Up the release of the OgmaNeo C++/OpenCL library, we used [SWIG](http://www.swig.org) to create language bindings for [Python](https://github.com/ogmacorp/PyOgmaNeo), [Java-JNI](https://github.com/ogmacorp/JOgmaNeo), and internally C#.

SWIG added support for Go in version 2.0.1 [1]. Allowing for C++ libraries to become packages that can be called from Go code. SWIG language bindings have varied and inconsistent support for C++1X and standard library features [2].

- One key feature we require with OgmaNeo is support of std::shared_ptr Unfortunately this is missing from Go support in SWIG.
- The other troublesome aspect is that the Go support in SWIG currently only works on Linux and Mac OS. An issue to add Windows support for Go in SWIG remains open [3, 4].

Refs:

1. SWIG Golang support - http://www.swig.org/Doc3.0/Go.html
2. SWIG Golang std lib support - https://github.com/swig/swig/tree/master/Lib/go
3. SWIG + CGO + Windows open issue - https://github.com/golang/go/issues/9095
4. https://groups.google.com/forum/#!topic/golang-nuts/-M-8X-PLvOw

Windows c-shared mode - https://github.com/golang/go/issues/11058
Go execution modes - https://groups.google.com/forum/#!topic/golang-dev/0_N7DLmrUFA

**Comment by nytopop** [comment]
I gave this a shot with SWIG and ran into the same roadblock, not having shared_ptr support for Go.

For my eval use case I ended up just writing bindings manually and converting from shared_ptr to raw pointers and cgo. It's a bit [hacky](https://github.com/nytopop/neogo) and doesn't cover the entire api, but works well enough for my purposes.

Thanks for looking into this.
