### ISSUE TITLE
Issues with the python build

### ISSUE THREAD

**Issue by AIAdventures** [ogmacorp/OgmaNeo#25]
hi all,
Testing the python import and getting the below error.
![screenshot_2017-07-12_15-50-43](https://user-images.githubusercontent.com/26102503/28103599-f1c4ea0e-6719-11e7-9a0a-7dd06bf94d24.png)

**Comment by rcrowder** [comment]
Hi @AIAdventures, thanks for posting the build log. The swig application does have it's own dependency on the PCRE library, so not being able to run swig shows an issue with it's installation. But more importantly all our language bindings require version 3+ of swig [1], where as your build is picking up v2 (`/usr/bin/swig2.0`).
Try installing version 3+ of swig and rerunning that build.


1 https://github.com/ogmacorp/OgmaNeo/tree/master/Python#requirements

**Comment by AIAdventures** [comment]
I tried installing the third version, but with no success. Some reason does
not work with Linux mint.
Any tips would be greatly appreciated 😃.
Many thanks,
Best,
Andrew

**Comment by rcrowder** [comment]
@AIAdventures I've just checked a Linux Mint 18.2 version. It looks like the easiest way to install SWIG on Mint is with the following -
> sudo apt purge swig
> sudo apt install libpcre3 libpcre3-dev  
> sudo apt install swig3.0  
> swig -version  

This is an older 3.0.8 version, but it works fine with OgmaNeo.

A more indepth way is to build the latest version 3.0.12 from original source code, using e.g. -
> mkdir temp  
> cd temp  
> sudo apt install libpcre3 libpcre3-dev  
> wget https://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz  
> tar xvf swig-3.0.12.tar.gz  
> cd swig-3.0.12/  
> ./configure  
> make
> sudo make install  
> swig -version

**Comment by rcrowder** [comment]
@AIAdventures I'm closing this issue. It relates to using v2 of Swig, whereas we require v3 of Swig when building the language bindings.
