### ISSUE TITLE
issues on arch linux

### ISSUE THREAD

**Issue by andrewcz** [ogmacorp/OgmaNeo#28]
- CMake install prefix = /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/3rdparty
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build
cd /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build && /usr/bin/cmake -E touch /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-stamp/OgmaNeoDownload-configure
[ 54%] Performing build step for 'OgmaNeoDownload'
cd /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build && /usr/bin/make
make[3]: Entering directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[4]: Entering directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[5]: Entering directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
Scanning dependencies of target OgmaOCLtoHpp
make[5]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[5]: Entering directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
[  3%] Building CXX object CMakeFiles/OgmaOCLtoHpp.dir/utils/OCLpp.cpp.o
In file included from /usr/include/c++/7.2.0/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7.2.0/bits/basic_string.h:6159,
                 from /usr/include/c++/7.2.0/string:52,
                 from /usr/include/c++/7.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/7.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/7.2.0/ios:42,
                 from /usr/include/c++/7.2.0/ostream:38,
                 from /usr/include/c++/7.2.0/iostream:39,
                 from /home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload/utils/OCLpp.cpp:9:
/usr/include/c++/7.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
make[5]: *** [CMakeFiles/OgmaOCLtoHpp.dir/build.make:63: CMakeFiles/OgmaOCLtoHpp.dir/utils/OCLpp.cpp.o] Error 1
make[5]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[4]: *** [CMakeFiles/Makefile2:100: CMakeFiles/OgmaOCLtoHpp.dir/all] Error 2
make[4]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[3]: *** [Makefile:130: all] Error 2
make[3]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload-build'
make[2]: *** [CMakeFiles/OgmaNeoDownload.dir/build.make:114: OgmaNeo/src/OgmaNeoDownload-stamp/OgmaNeoDownload-build] Error 2
make[2]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6'
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/OgmaNeoDownload.dir/all] Error 2
make[1]: Leaving directory '/home/andrewcz/ogmaneo/Python/build/temp.linux-x86_64-3.6'
make: *** [Makefile:133: all] Error 2
error: command 'cmake' failed with exit status 2
[andrewcz@andrewcz-pc Python]$

**Comment by rcrowder** [comment]
Hi @andrewcz From what I can tell, this may be a change in GCC v6+, that changed system wide include headers and how CMake handles them [1]. I've a hot-fix almost ready that may help with this issue. I'll @ping you when that fix is pushed and ready for you to try again..

1: https://gitlab.kitware.com/cmake/cmake/issues/16291

**Comment by andrewcz** [comment]
cheers Richard!
Sincerely appreciated :).
Best,
Andrew

**Comment by rcrowder** [comment]
@andrewcz I recreated this issue using GCC 7 with Linux Mint 18.2 and merged in changes to solve it. I confident that this latest release [1] solves the problem, so'll close this issue off. Let me know if you still face a problem with this, once you've updated your clone/fork of the repo.

1 https://github.com/ogmacorp/OgmaNeo/releases/tag/v1.4.2

**Comment by andrewcz** [comment]
build successful!!
cheers, Richard!
Amazing work.
Best,
Andrew
