### ISSUE TITLE
small python issues

### ISSUE THREAD

**Issue by andrewcz** [ogmacorp/OgmaNeo#30]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6
cmake --build . --config Release
/usr/bin/cmake -H/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python -B/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/CMakeFiles /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
/usr/bin/make -f CMakeFiles/OgmaNeoDownload.dir/build.make CMakeFiles/OgmaNeoDownload.dir/depend
make[2]: Entering directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
cd /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6 /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6 /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/CMakeFiles/OgmaNeoDownload.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
/usr/bin/make -f CMakeFiles/OgmaNeoDownload.dir/build.make CMakeFiles/OgmaNeoDownload.dir/build
make[2]: Entering directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
[  9%] Performing update step for 'OgmaNeoDownload'
cd /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/OgmaNeo/src/OgmaNeoDownload && /usr/bin/cmake -P /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/OgmaNeo/tmp/OgmaNeoDownload-gitupdate.cmake

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@andrewcz-pc.(none)')
Cannot save the current index state
CMake Error at /home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6/OgmaNeo/tmp/OgmaNeoDownload-gitupdate.cmake:83 (message):
  Failed to stash changes

make[2]: *** [CMakeFiles/OgmaNeoDownload.dir/build.make:98: OgmaNeo/src/OgmaNeoDownload-stamp/OgmaNeoDownload-update] Error 1
make[2]: Leaving directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/OgmaNeoDownload.dir/all] Error 2
make[1]: Leaving directory '/home/andrewcz/Downloads/OgmaNeo-1.4.2/Python/build/temp.linux-x86_64-3.6'
make: *** [Makefile:133: all] Error 2
error: command 'cmake' failed with exit status 2
[andrewcz@andrewcz-pc Python]$

**Comment by rcrowder** [comment]
Hi @andrewcz Thanks for posting this log. Typically you only do this setup of Git once [1], and then that log message from Git isn't shown after that.

Although this does show that the CMake script can be improved when it tries to find a locally built and system-wide installed version of the C++ library. In this instance, it won't make a difference. In that whether it finds a local install, or downloads the latest release, the binding(s) will both end up using the same library version. But I will improve the CMake scripts to help with this situation and add that to any future release that's made here.

1: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by andrewcz** [comment]
This issue can be closed.
Cheers Richard!
Best,
Andrew
