### ISSUE TITLE
another small issue

### ISSUE THREAD

**Issue by andrewcz** [ogmacorp/OgmaNeo#31]
[andrewcz@andrewcz-pc Python]$ ls
build  CMakeLists.txt  Example.py  Gym.py  ModuleTest.py  ogmaneo.egg-info  pyogmaneo.i  README.md  requirements.txt  setup.cfg  setup.py  WavyDemo.py
[andrewcz@andrewcz-pc Python]$ python Example.py 
OgmaNeo version: 1.4.2
Found 1 platform(s).
Platform 0: Intel(R) OpenCL
Using platform: Intel(R) OpenCL

Found 1 device(s).
Device 0: Intel(R) HD Graphics
Using device: Intel(R) HD Graphics

Segmentation fault (core dumped)
[andrewcz@andrewcz-pc Python]$ python WavyDemo.py 
OgmaNeo version: 1.4.2
Found 1 platform(s).
Platform 0: Intel(R) OpenCL
Using platform: Intel(R) OpenCL

Found 1 device(s).
Device 0: Intel(R) HD Graphics
Using device: Intel(R) HD Graphics

Segmentation fault (core dumped)
[andrewcz@andrewcz-pc Python]$

**Comment by andrewcz** [comment]
i am back at this one.
is my card not supported?

**Comment by andrewcz** [comment]
[andrewcz@andrewcz-pc Python]$ python WavyDemo.py 
OgmaNeo version: 1.4.2
Found 2 platform(s).
Platform 0: Intel(R) OpenCL
Platform 1: Intel Gen OCL Driver
Using platform: Intel Gen OCL Driver

Found 1 device(s).
Device 0: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2
Using device: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2

Segmentation fault (core dumped)
[andrewcz@andrewcz-pc Python]$

**Comment by rcrowder** [comment]
@andrewcz Your card is supported. I use an Intel HD 5xx series GPU for testing the library and demos (albeit using Windows drivers).

Getting to the point of running the Python scripts, and it displaying the OgmaNeo version, shows that you have an OpenCL SDK installed ok and OgmaNeo library and bindings building ok.

There are two things you can do to help diagnose the seg-fault:

1. Tell OgmaNeo to use a CPU rather than a GPU. That involves finding the following line in the Python scripts `res.create(ogmaneo.ComputeSystem._gpu)` and changing `_gpu` to `_cpu`
2. Use the `clinfo` executable (likely need to `sudo apt install clinfo`) to ask OpenCL on you system what platforms and devices exist, and importantly what they are capable of.

Be aware that the first option may still seg-fault. The potential cause here is lack of up-to-date/generic graphics drivers. It'd be great if you can post here the log produced by the `./clinfo` command.

**Comment by andrewcz** [comment]
[andrewcz@andrewcz-pc ~]$ clinfo
Number of platforms                               2
  Platform Name                                   Intel(R) OpenCL
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel(R) OpenCL
Number of devices                                 2
  Device Name                                     Intel(R) HD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 
  Driver Version                                  r4.1.61547
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Available                                Yes
  Device Profile                                  FULL_PROFILE
  Max compute units                               24
  Max clock frequency                             900MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Compiler Available                              Yes
  Linker Available                                Yes
Segmentation fault (core dumped)
[andrewcz@andrewcz-pc ~]$

**Comment by andrewcz** [comment]
[andrewcz@andrewcz-pc Python]$ python Example.py 
OgmaNeo version: 1.4.2
Found 2 platform(s).
Platform 0: Intel(R) OpenCL
Platform 1: Intel Gen OCL Driver
Using platform: Intel Gen OCL Driver

Found 1 device(s).
Device 0: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2
Using device: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2

Stepping the hierarchy...
Segmentation fault (core dumped)
[andrewcz@andrewcz-pc Python]$ 


when i changed it to 

Tell OgmaNeo to use a CPU rather than a GPU. That involves finding the following line in the Python scripts res.create(ogmaneo.ComputeSystem._gpu) and changing _gpu to _cpu

**Comment by rcrowder** [comment]
@andrewcz Yeah the clinfo seg-fault certainly shows that something isn't correct with your OpenCL drivers (part of a GPU driver package). It should show quite a bit more information about the capabilities of your OpenCL devices.
By default the `res.create()` call sets a second and third parameter [1] to `-1` and that forces OgmaNeo to use the highest platform and device. So you can try using `res.create(ogmaneo.ComputeSystem._gpu, 0, 0)`, for example.
But your original post and clinfo failure points at some problem with your graphics driver installation. Other than making sure that your driver (and kernel?) is up to date, the only other thing to suggest is to use our more recent EOgmaNeo library that doesn't rely on OpenCL/GPU.

1 https://github.com/ogmacorp/OgmaNeo/blob/master/source/system/ComputeSystem.cpp#L15
