### ISSUE TITLE
strange error - arch linux

### ISSUE THREAD

**Issue by andrewcz** [ogmacorp/OgmaNeo#32]
[andrewcz@andrewcz-pc ~]$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ogmaneo
>>> 
KeyboardInterrupt
>>> 
[andrewcz@andrewcz-pc ~]$ cd Downloads/
[andrewcz@andrewcz-pc Downloads]$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ogmaneo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ogmaneo'
>>>

**Comment by rcrowder** [comment]
@andrewcz It looks from your other issues posted here that you have the Python examples running (in that the show the Python OgmaNeo package version, and get to the "Found..." platforms output). So I'm unsure how the Python interpreter cannot import OgmaNeo. Does it show up when you type `pip show ogmaneo`?

**Comment by andrewcz** [comment]
the above can be closed

**Comment by rcrowder** [comment]
Thanks @andrewcz
