### ISSUE TITLE
PyOgmaNeo Gym.py example not working

### ISSUE THREAD

**Issue by orolle** [ogmacorp/OgmaNeo#34]
the Gym.py example is not working due to API changes.

**Comment by rcrowder** [comment]
@orolle Hi, unfortunately we've had to remove that older Gym.py example. It was set up to use version 1.2 of OgmaNeo. But the big changes we introduced into v1.3 (exponential memory, delay encoder, and retirement of the swarming agent) means that it is now no longer set up for the latest release, and we don't foresee adding reinforcement learning back into OgmaNeo in the near future. Our current focus and attention is within the https://github.com/ogmacorp/EOgmaNeo repo.
