### ISSUE TITLE
Port to vanilla C++

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeo#7]
To study how this approach works I've copied the sources and removed all dependencies. What remains are 13 header files, no OpenCL nor flatbuffers just vanilla C++ code. 

Question: how should I make my project public. Would it be ok if I add it to my fork? I assume that it would than have the licencing of the parent project, but I could be mistaken.

Regards HJ!

**Comment by rcrowder** [comment]
Hi @HJLebbink We have also experimented with C++ only versions of OgmaNeo. Our early prototyping was carried out in Python, before moving that into OpenCL kernel code and C++
To see your changes it would need to be placed in a branch on your fork. There are copyright and license issues to take into account.

**Comment by HJLebbink** [comment]
Yes, my question is about the licence. I don't mind sticking a Ogma licence on all files (or whatever suites you best). What works best for you?

**Comment by rcrowder** [comment]
@HJLebbink To accept changes back into the library, we do require that additional files include the copyright and license headers. Alongside a signed [Contributor Agreement](https://ogma.ai/wp-content/uploads/2016/09/OgmaContributorAgreement.pdf), to assist with handling copyright assignment.
The best for us is for you to add the headers into your additional files. Once we can see the additions and changes made we can discuss further how that work could be absorbed back into this repository.
Internally we also have an older port to vanilla C++ that we originally created for devices such as the Raspberry Pi3 (before use of the [pocl](http://portablecl.org/) driver). We're discussing whether that work should be released at some point, dependent on a community led version such as your port.
Bear in mind that internally we are currently designing and augmenting the high level interface(s) to ease the release of further work and improvements. In part this will affect the port you currently have to vanilla C++

**Comment by HJLebbink** [comment]
Hi Richard,

https://github.com/HJLebbink/Feynman-cpp has my current version.
