### ISSUE TITLE
Implementation questions 

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeo#8]
Thank you for sharing this research. While studying it I've noticed some small issues or I had questions. 

FeatureHierarchy.cpp: line 91: can 
"for (int l = 0; l < _layers.size(); l++)"
be replaced with: 
"if (learn) for (int l = 0; l < _layers.size(); l++)"

neoKernelsMain.cl: line 364: can
"write_imagef(weightsFront, (int4)(hiddenPosition.x, hiddenPosition.y, wi, 0), (float4)(weight));"
be replaced with:
"write_imagef(weightsFront, (int4)(hiddenPosition.x, hiddenPosition.y, wi, 0), (float4)(weight, 0.0f, 0.0f, 0.0f));

neoKernelsExtra.cl: line 193: can 
"write_imagef(hiddenSummationTempFront, hiddenPosition, (float4)(sum + subSum / fmax(1.0f, count)));
be replaced with:
"write_imagef(hiddenSummationTempFront, hiddenPosition, (float4)(sum + subSum / fmax(1.0f, count), 0.0f, 0.0f, 0.0f));

neoKernelsExtra.cl: line 270: can 
"write_imagef(hiddenStatesFront, hiddenPosition, (float4)(state));
be replaced with:
"write_imagef(hiddenStatesFront, hiddenPosition, (float4)(state, 0.0f, 0.0f, 0.0f));

neoKernelsExtra.cl: line 299: can 
"write_imagef(weightsFront, (int4)(hiddenPosition.x, hiddenPosition.y, wi, 0), (float4)(weightPrev + weightAlpha \* hiddenState \* reconError));"
be replaced with:
"write_imagef(weightsFront, (int4)(hiddenPosition.x, hiddenPosition.y, wi, 0), (float4)(weightPrev + weightAlpha \* hiddenState \* reconError, 0.0f, 0.0f, 0.0f));

**Comment by rcrowder** [comment]
@HJLebbink Yes, all those changes can be made.
The `FeatureHierarchy::simStep` class declaration defaults the `learn` parameter to true. A case exists as to whether to remove the parameter, or as you describe to use it to optionally turn off layer learning.
A `float4` constructed with a single floating point value replicates that value into yzw fields (or gba). In the instances highlighted above, all the images referred to in the `write_imagef` calls are created with one channel (`CL_R`). All fields can be the same (current code), or set to zero. Internally the OpenCL driver `write_imagef` function deals with the singular or multi channel image writes. Subsequent `read_imagef` calls for these particular images only access the first channel (`.x` modifier). I'm unsure whether specifically setting those values to zero would add additional overhead.

**Comment by HJLebbink** [comment]
Hi Richard,
Thank you. When rewriting all OpenCL code I first assumed (based on the CL_R) that only the first float from float4 was used. However, kernel scDeriveInputs reads (and write) the second float. I then had to check whether scDeriveInputs was the only place where this second float was written. Hence the question.

```
void kernel scDeriveInputs(read_only image2d_t inputs, read_only image2d_t outputsBack, write_only image2d_t outputsFront, float lambda) {
    int2 position = (int2)(get_global_id(0), get_global_id(1));
    float input = read_imagef(inputs, defaultSampler, position).x
    float2 outputPrev = read_imagef(outputsBack, defaultSampler, position).xy;
    write_imagef(outputsFront, position, (float4)(input, lambda * outputPrev.y + (1.0f - lambda) * input, 0.0f, 0.0f));
} 

```
